language: php
php:
- 5.4
env:
  matrix:
  - BROWSER_TYPE: firefox
  - BROWSER_TYPE: chrome
  - BROWSER_TYPE: internetexplorer
  - BROWSER_TYPE: opera
  global:
  - secure: Ca3EYUlYvp7ZhcyajnV8x0PSFtqa+l2I2eAZu3RZJeKScRwgndOserZEgNRkBSaRMdQL8JmUsj7vQTUPfTUvk0OQ+3y5m+I7W2DeX1Y0EGfQAR4k9IorLvN1fbDsJ0jHC49KodWL+ehEoqz23fVEi4RgoQkM6Nz6WQlprlz1BCo=
  - secure: XvyNsZB+VvMNTTi9z95CXmnuSAypLHLXzkK8+gf0IOUm2MfOAYe+jHGxWhOhu+kZHQ5zimRCPeRbaziM7YQiq18TBjLBmotazAyiEEGuP0z50oNxO3z1Ch3IFKWBvq4cpE066P9KmM/jBt7P5K7yiOIoscCfjOO7saSZFOzYhcI=
addons:
  sauce_connect: true
before_install:
- sudo apt-get -qq update
- sudo apt-get install build-essential libpcap-dev
- sudo apt-get install nginx php5-fpm
- sudo cp testing/nginx.conf /etc/nginx/nginx.conf
- sudo /etc/init.d/nginx restart
- sudo mkdir -p /var/www
- sudo chown www-data:www-data /var/www
install:
- git clone https://github.com/splitice/p0f.git -b ssl
- cd p0f
- sudo make
- export MAC_EXPR=$(ifconfig -a | grep "HWaddr " | grep -v "HWaddr 00:00:00:00:00:00" | grep "Link encap:Ethernet" | awk '{tmp=match($0,/HWaddr ([0-9a-f]{2}\:[0-9a-f]{2}\:[0-9a-f]{2}\:[0-9a-f]{2}\:[0-9a-f]{2}\:[0-9a-f]{2})/,m);print "ether dst "m[1]}' | sort | uniq | awk -vORS=" || " '{print $0}' | sed 's/ || $/\n/')
- sudo ./p0f -s /var/run/p0f.sock -f ../p0f.fp -i lo -d "tcp port 80 && ($MAC_EXPR)" 
- cd ..
- sudo cp testing/test.php /var/www/
- sudo chown www-data:www-data /var/www/test.php
script:
- cd testing
- composer install
- curl -v http://127.0.0.1/test.php
#- vendor/bin/paratest -p 5 -f --configuration="phpunit.xml" --phpunit="vendor/bin/phpunit"
- vendor/bin/phpunit -v -c phpunit.xml