language: php
php:
- 5.4
env:
  global:
  - secure: Ca3EYUlYvp7ZhcyajnV8x0PSFtqa+l2I2eAZu3RZJeKScRwgndOserZEgNRkBSaRMdQL8JmUsj7vQTUPfTUvk0OQ+3y5m+I7W2DeX1Y0EGfQAR4k9IorLvN1fbDsJ0jHC49KodWL+ehEoqz23fVEi4RgoQkM6Nz6WQlprlz1BCo=
  - secure: XvyNsZB+VvMNTTi9z95CXmnuSAypLHLXzkK8+gf0IOUm2MfOAYe+jHGxWhOhu+kZHQ5zimRCPeRbaziM7YQiq18TBjLBmotazAyiEEGuP0z50oNxO3z1Ch3IFKWBvq4cpE066P9KmM/jBt7P5K7yiOIoscCfjOO7saSZFOzYhcI=
addons:
  sauce_connect: true
before_install:
- sudo apt-get update
- sudo apt-get install build-essential libpcap-dev
- sudo apt-get install nginx php5-fpm
- sudo cp testing/nginx.conf /etc/nginx/nginx.conf
- sudo /etc/init.d/nginx restart
- sudo mkdir -p /var/www
- sudo chown www-data:www-data /var/www
install:
- git clone https://github.com/splitice/p0f.git -b ssl
- cd p0f
- sudo make
- sudo ./p0f -d -s /var/run/p0f.sock -f ../p0f.fp
- cd ..
- sudo cp testing/test.php /var/www/
- sudo chown www-data:www-data /var/www/test.php
- curl -s https://raw.github.com/jlipps/sausage-bun/master/givememysausage.php | php
script:
- phpunit --verbose -c tests/phpunit.xml